apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-test-oct30-app
  namespace: ai-rhdh
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./components/rag-test-oct30/overlays/development
    repoURL: https://github.com/jdubrick-ai/rag-test-oct30-gitops.git
    targetRevision: main
  destination:
    namespace: rhdh-test
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: ai-rhdh
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
