apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: rag-test-oct30 
  janus-idp.io/tekton: rag-test-oct30
  backstage.io/kubernetes-id: rag-test-oct30
  backstage.io/kubernetes-namespace: rhdh-test 
  app.kubernetes.io/part-of: rag-test-oct30
resources: 
- application-dev.yaml