kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rag-test-oct30-imagestream-job-rolebinding
  namespace: redhat-ods-applications
subjects:
  - kind: ServiceAccount
    name: rag-test-oct30-dsp-job
    namespace: rhdh-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rag-test-oct30-imagestream-job-role
